# Site settings
title: Imanol Aranzadi
email: iiaranzadi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will be an awesome description, coliphonikipo!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iaranzadi.com" # the base hostname & protocol for your site
twitter_username: iaranzadi
github_username:  inaki

# Build settings
markdown: kramdown
