# Site settings
title: I am Iñaki
email: iiaranzadi@gmail.com
description: > # Iñaki Aranzadi Web Developer Portfolio Page

url:              http://www.iaminaki.com
baseurl:          /


twitter_username: iaranzadi
github_username:  inaki

# Build settings
markdown: kramdown
